# Generated by Django 4.1 on 2022-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stake_overflow',
            field=models.URLField(null=True),
        ),
    ]
