# Generated by Django 4.1 on 2022-08-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rereply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('uuid', 'title')},
        ),
    ]
